// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sf/substreams/sink/kv/v1/read.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/streamingfast/substreams-sink-kv/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// KvName is the fully-qualified name of the Kv service.
	KvName = "sf.substreams.sink.kv.v1.Kv"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// KvGetProcedure is the fully-qualified name of the Kv's Get RPC.
	KvGetProcedure = "/sf.substreams.sink.kv.v1.Kv/Get"
	// KvGetManyProcedure is the fully-qualified name of the Kv's GetMany RPC.
	KvGetManyProcedure = "/sf.substreams.sink.kv.v1.Kv/GetMany"
	// KvGetByPrefixProcedure is the fully-qualified name of the Kv's GetByPrefix RPC.
	KvGetByPrefixProcedure = "/sf.substreams.sink.kv.v1.Kv/GetByPrefix"
	// KvScanProcedure is the fully-qualified name of the Kv's Scan RPC.
	KvScanProcedure = "/sf.substreams.sink.kv.v1.Kv/Scan"
)

// KvClient is a client for the sf.substreams.sink.kv.v1.Kv service.
type KvClient interface {
	// Get returns the requested value as bytes if it exists, grpc_error: NOT_FOUND otherwise.
	Get(context.Context, *connect_go.Request[pb.GetRequest]) (*connect_go.Response[pb.GetResponse], error)
	// GetMany returns the requested values as bytes if all of them exists, grpc_error: NOT_FOUND otherwise.
	GetMany(context.Context, *connect_go.Request[pb.GetManyRequest]) (*connect_go.Response[pb.GetManyResponse], error)
	// GetByPrefix returns the next _limit_ key/value pair that match the requested prefix if any exist, grpc_error: NOT_FOUND otherwise.
	GetByPrefix(context.Context, *connect_go.Request[pb.GetByPrefixRequest]) (*connect_go.Response[pb.GetByPrefixResponse], error)
	// Scan returns then next _limit_ key/value pairs starting lexicographically at the given key, grpc_error: NOT_FOUND otherwise.
	Scan(context.Context, *connect_go.Request[pb.ScanRequest]) (*connect_go.Response[pb.ScanResponse], error)
}

// NewKvClient constructs a client for the sf.substreams.sink.kv.v1.Kv service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKvClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) KvClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &kvClient{
		get: connect_go.NewClient[pb.GetRequest, pb.GetResponse](
			httpClient,
			baseURL+KvGetProcedure,
			opts...,
		),
		getMany: connect_go.NewClient[pb.GetManyRequest, pb.GetManyResponse](
			httpClient,
			baseURL+KvGetManyProcedure,
			opts...,
		),
		getByPrefix: connect_go.NewClient[pb.GetByPrefixRequest, pb.GetByPrefixResponse](
			httpClient,
			baseURL+KvGetByPrefixProcedure,
			opts...,
		),
		scan: connect_go.NewClient[pb.ScanRequest, pb.ScanResponse](
			httpClient,
			baseURL+KvScanProcedure,
			opts...,
		),
	}
}

// kvClient implements KvClient.
type kvClient struct {
	get         *connect_go.Client[pb.GetRequest, pb.GetResponse]
	getMany     *connect_go.Client[pb.GetManyRequest, pb.GetManyResponse]
	getByPrefix *connect_go.Client[pb.GetByPrefixRequest, pb.GetByPrefixResponse]
	scan        *connect_go.Client[pb.ScanRequest, pb.ScanResponse]
}

// Get calls sf.substreams.sink.kv.v1.Kv.Get.
func (c *kvClient) Get(ctx context.Context, req *connect_go.Request[pb.GetRequest]) (*connect_go.Response[pb.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// GetMany calls sf.substreams.sink.kv.v1.Kv.GetMany.
func (c *kvClient) GetMany(ctx context.Context, req *connect_go.Request[pb.GetManyRequest]) (*connect_go.Response[pb.GetManyResponse], error) {
	return c.getMany.CallUnary(ctx, req)
}

// GetByPrefix calls sf.substreams.sink.kv.v1.Kv.GetByPrefix.
func (c *kvClient) GetByPrefix(ctx context.Context, req *connect_go.Request[pb.GetByPrefixRequest]) (*connect_go.Response[pb.GetByPrefixResponse], error) {
	return c.getByPrefix.CallUnary(ctx, req)
}

// Scan calls sf.substreams.sink.kv.v1.Kv.Scan.
func (c *kvClient) Scan(ctx context.Context, req *connect_go.Request[pb.ScanRequest]) (*connect_go.Response[pb.ScanResponse], error) {
	return c.scan.CallUnary(ctx, req)
}

// KvHandler is an implementation of the sf.substreams.sink.kv.v1.Kv service.
type KvHandler interface {
	// Get returns the requested value as bytes if it exists, grpc_error: NOT_FOUND otherwise.
	Get(context.Context, *connect_go.Request[pb.GetRequest]) (*connect_go.Response[pb.GetResponse], error)
	// GetMany returns the requested values as bytes if all of them exists, grpc_error: NOT_FOUND otherwise.
	GetMany(context.Context, *connect_go.Request[pb.GetManyRequest]) (*connect_go.Response[pb.GetManyResponse], error)
	// GetByPrefix returns the next _limit_ key/value pair that match the requested prefix if any exist, grpc_error: NOT_FOUND otherwise.
	GetByPrefix(context.Context, *connect_go.Request[pb.GetByPrefixRequest]) (*connect_go.Response[pb.GetByPrefixResponse], error)
	// Scan returns then next _limit_ key/value pairs starting lexicographically at the given key, grpc_error: NOT_FOUND otherwise.
	Scan(context.Context, *connect_go.Request[pb.ScanRequest]) (*connect_go.Response[pb.ScanResponse], error)
}

// NewKvHandler builds an HTTP handler from the service implementation. It returns the path on which
// to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKvHandler(svc KvHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(KvGetProcedure, connect_go.NewUnaryHandler(
		KvGetProcedure,
		svc.Get,
		opts...,
	))
	mux.Handle(KvGetManyProcedure, connect_go.NewUnaryHandler(
		KvGetManyProcedure,
		svc.GetMany,
		opts...,
	))
	mux.Handle(KvGetByPrefixProcedure, connect_go.NewUnaryHandler(
		KvGetByPrefixProcedure,
		svc.GetByPrefix,
		opts...,
	))
	mux.Handle(KvScanProcedure, connect_go.NewUnaryHandler(
		KvScanProcedure,
		svc.Scan,
		opts...,
	))
	return "/sf.substreams.sink.kv.v1.Kv/", mux
}

// UnimplementedKvHandler returns CodeUnimplemented from all methods.
type UnimplementedKvHandler struct{}

func (UnimplementedKvHandler) Get(context.Context, *connect_go.Request[pb.GetRequest]) (*connect_go.Response[pb.GetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("sf.substreams.sink.kv.v1.Kv.Get is not implemented"))
}

func (UnimplementedKvHandler) GetMany(context.Context, *connect_go.Request[pb.GetManyRequest]) (*connect_go.Response[pb.GetManyResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("sf.substreams.sink.kv.v1.Kv.GetMany is not implemented"))
}

func (UnimplementedKvHandler) GetByPrefix(context.Context, *connect_go.Request[pb.GetByPrefixRequest]) (*connect_go.Response[pb.GetByPrefixResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("sf.substreams.sink.kv.v1.Kv.GetByPrefix is not implemented"))
}

func (UnimplementedKvHandler) Scan(context.Context, *connect_go.Request[pb.ScanRequest]) (*connect_go.Response[pb.ScanResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("sf.substreams.sink.kv.v1.Kv.Scan is not implemented"))
}
